/**
 * Date: 3/12/18
 * Time: 9:50 PM
 * @license MIT (see project's LICENSE file)
 */

import {STATUS_CODES} from "http";


/**
 * Some popular HTTP methods
 */
export enum HttpMethod {
	CONNECT = "CONNECT",
	DELETE = "DELETE",
	GET = "GET",
	HEAD = "HEAD",
	OPTIONS = "OPTIONS",
	POST = "POST",
	PUT = "PUT"
}

export enum HttpStatusCode {
	CONTINUE = 100,
	SWITCHING_PROTOCOLS = 101,
	PROCESSING = 102,
	OK = 200,
	CREATED = 201,
	ACCEPTED = 202,
	RESET_CONTENT = 205,
	NON_AUTHORITATIVE_INFORMATION = 203,
	NO_CONTENT = 204,
	PARTIAL_CONTENT = 206,
	MULTI_STATUS = 207,
	MULTIPLE_CHOICES = 300,
	MOVED_PERMANENTLY = 301,
	MOVED_TEMPORARILY = 302,
	SEE_OTHER = 303,
	NOT_MODIFIED = 304,
	USE_PROXY = 305,
	TEMPORARY_REDIRECT = 307,
	PERMANENT_REDIRECT = 308,
	UNAUTHORIZED = 401,
	BAD_REQUEST = 400,
	PAYMENT_REQUIRED = 402,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
	METHOD_NOT_ALLOWED = 405,
	NOT_ACCEPTABLE = 406,
	PROXY_AUTHENTICATION_REQUIRED = 407,
	CONFLICT = 409,
	GONE = 410,
	LENGTH_REQUIRED = 411,
	METHOD_FAILURE = 420,
	REQUEST_TIMEOUT = 408,
	REQUEST_TOO_LONG = 413,
	REQUEST_URI_TOO_LONG = 414,
	REQUESTED_RANGE_NOT_SATISFIABLE = 416,
	UNSUPPORTED_MEDIA_TYPE = 415,
	PRECONDITION_FAILED = 412,
	EXPECTATION_FAILED = 417,
	INSUFFICIENT_SPACE_ON_RESOURCE = 419,
	UNPROCESSABLE_ENTITY = 422,
	LOCKED = 423,
	FAILED_DEPENDENCY = 424,
	PRECONDITION_REQUIRED = 428,
	TOO_MANY_REQUESTS = 429,
	REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
	INTERNAL_SERVER_ERROR = 500,
	NOT_IMPLEMENTED = 501,
	BAD_GATEWAY = 502,
	SERVICE_UNAVAILABLE = 503,
	GATEWAY_TIMEOUT = 504,
	HTTP_VERSION_NOT_SUPPORTED = 505,
	INSUFFICIENT_STORAGE = 507,
	NETWORK_AUTHENTICATION_REQUIRED = 511
}

export function httpStatusCodeToText(code: number, dfault: string = code.toString()): string {
	return (code in STATUS_CODES)
		? STATUS_CODES[code] as string
		: dfault;
}
